# name: Publish docs via GitHub Pages
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Deploy docs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout main
#         uses: actions/checkout@v3
#         with:
#           submodules: 'true'

#       - name: Deploy docs
#         uses: mhausenblas/mkdocs-deploy-gh-pages@master
#         with:
#           submodules: 'true'
#         # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           CUSTOM_DOMAIN: https://pizza.jacensolo.com
#           CONFIG_FILE: mkdocs.yml
#           EXTRA_PACKAGES: build-base
#           REQUIREMENTS: folder/requirements.txt

name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          # key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: python3 -m pip install -r #./requirements.txt

      - run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/gh-pages'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
